### ISSUE TITLE
cloudgene features proposal

### ISSUE THREAD

**Issue by dridk** [jhuckaby/Cronicle#429]
Hi, 

I m a bioinformatician and I have used your greate cronicle application to launch my pipelines analysis. 
I switched to cloudgene http://www.cloudgene.io/ recently because it has a good feature for creating job with formular.

cloudgene propose a yaml format to describe how to run a script with an input. This input description is used later to generate a form . 

```yaml
id: MyExecutable
name: My executable
description: Execute my script 
category: groupA
version: 1.0
workflow:
    steps:
      - name: Step 1
        cmd: /usr/bin/bash  /bin/run_my_script.sh $input
    inputs:
      - id: input
        description: a string message 
        type: text
```

This script can be run from command-line for testing purpose:

```bash
cloudgene run MyExecutable --input "hello word" 
```

Then, the web interface uses this plugin to build a web form : 
 
![image](https://user-images.githubusercontent.com/1911063/125770909-2a88ecd5-5025-410d-939f-e939c1564379.png)

From cronicle, it is not easy to create a job from a formular. I can create my own webpage and start a job from the REST API. But this should be done by cronicle automatically.
