### ISSUE TITLE
minor css issues (chromium)

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#475]
I noticed that horizontal lines with 1px size are not rendered consistently on **Chromium** browsers, so data tables look a bit quirky.

this style affects table border:
```css
border-bottom: 1px solid var(--border-color)
```
and this affects table spacer
```css
.table_spacer { height: 1px }
```
One option to fix this is to change 1px to 0.1px 

Those styles mainly come from pixl-app, so need to fix it there.

Another CSS related  thing - it would be helpful to add row highlighting on mouse up (e.g. like on github issue list). On some data tables with actions, you typically see event id on the left side and action button on the right, so it's not that hard to click on the wrong event action. Sample style:
```css
		.data_table tr:hover td {
			background-color: #f0f0f0 !important;
			transition-delay: 30ms;
		}
```
